# Generated by Django 4.0.4 on 2022-05-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task Title', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.TextField(max_length=50)),
                ('profile', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='seller/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of project ', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(help_text='The price ')),
                ('photo', models.ImageField(upload_to='product/photos/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.seller')),
            ],
        ),
    ]
