# Generated by Django 4.0.4 on 2022-05-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='this is the seller first name', max_length=25)),
                ('last_name', models.CharField(help_text='this is the seller last name', max_length=25)),
                ('email', models.EmailField(help_text='this is the seller email', max_length=254)),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='this is seller registration_date')),
                ('seller_profile_pic', models.ImageField(upload_to='sellers_profile_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this the prodect name', max_length=25)),
                ('description', models.TextField(help_text='this a prodect discription')),
                ('quantity', models.IntegerField(help_text='this the prodect amount')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='this is seller registration_date')),
                ('product_img', models.ImageField(upload_to='products_img')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.seller')),
            ],
        ),
    ]
