# Generated by Django 4.0.4 on 2022-05-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(help_text='age seller')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='this is description')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.seller')),
            ],
        ),
    ]
